name: SuperKart Sales Forecasting MLOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Upload Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_REPO_ID: ${{ secrets.HF_DATASET_REPO_ID }}
        run: python model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Prepare Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_REPO_ID: ${{ secrets.HF_DATASET_REPO_ID }}
        run: python model_building/prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Train and Register Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_REPO_ID: ${{ secrets.HF_DATASET_REPO_ID }}
          HF_MODEL_REPO_ID: ${{ secrets.HF_MODEL_REPO_ID }}
        run: python model_building/model_build.py

  deploy-space:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Deploy Streamlit App to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO_ID: ${{ secrets.SPACE_REPO_ID }}
        run: python hosting/hosting.py
